feat(slate): add h4 in slate toolbar, refs #265544
eea/volto-eea-website-theme pull request #219
Opened 2024-03-20 10:11 UTC by razvanMiu

2024-03-20 17:12 UTC, ichim-david requested changes
@razvanMiu as discussed we will need to still use an h3 but with a special class

2024-03-21 13:12 UTC, ichim-david requested changes
@razvanMiu there is a problem with the rendering of anchors, the anchor is added after the text while in the other headers they are added before.
Here is how the anchor looks if it's added last thus
![rendering-anchor](https://github.com/eea/volto-eea-website-theme/assets/152852/7f1ac099-198c-4190-849a-af8d3a808eb2)

2024-03-21 14:47 UTC, ichim-david approved these changes
After modifying the title of the icon and the icon itself plus ensuring that we always use the volto-anchors rendering which removed the issue with the anchor being on top of the heading because it was added to the right the feature is ok in tandem with the changes from volto-eea-design-system

2024-03-25 13:12 UTC, avoinea approved these changes

2024-03-25 13:54 UTC, merged